apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
  namespace: development
spec:
  params:
    - default: https://github.com/TiagoAvelino/HelloWorldProject.git
      description: git url to clone
      name: git-source-url
      type: string
    - default: development
      name: dev-proj
      type: string
      description: name of the development project
    - default: develop
      description: "git revision to checkout (branch, tag, sha, refâ€¦)"
      name: git-source-revision
      type: string
    - default: hello-quarkus
      description: image name deve ser o valor do caminho final do image path
      name: image-name
      type: string
    - default: image-registry.openshift-image-registry.svc:5000/development/hello-quarkus
      description: image path
      name: remote-image
      type: string
    - default: my-java-quarkus
      name: deployment-name
      type: string
      description: name of the deployment to be patched
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-source-url)
        - name: revision
          value: $(params.git-source-revision)
        - name: sslVerify
          value: "false"
        - name: noProxy
          value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
    - name: run-test-cases
      params:
        - name: GOALS
          value:
            - clean
            - test
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: app-source
        - name: maven-settings
          workspace: maven-settings
    - name: build-artifact
      params:
        - name: GOALS
          value:
            - "-DskipTests"
            - package
            - "-Dquarkus.native.container-build=true"
      runAfter:
        - run-test-cases
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: app-source
        - name: maven-settings
          workspace: maven-settings
    - name: build-push-image
      params:
        - name: IMAGE
          value: $(params.remote-image)
        - name: TLSVERIFY
          value: "false"
      runAfter:
        - build-artifact
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: app-source
    - name: apply-manifests
      taskRef:
        name: apply-manifests
      runAfter:
        - build-push-image
      workspaces:
        - name: source
          workspace: app-source
    - name: get-current-time
      taskRef:
        name: print-date
      runAfter:
        - apply-manifests
    - name: update-deployment-dev
      taskRef:
        name: update-deployment
      params:
        - name: deployment
          value: $(params.deployment-name)
        - name: IMAGE
          value: $(params.remote-image):$(tasks.get-current-time.results.current-date-unix)
      runAfter:
        - get-current-time
    - name: tag-image
      params:
        - name: SCRIPT
          value: >-
            oc tag $(params.dev-proj)/$(params.image-name):latest
            $(params.dev-proj)/$(params.image-name):$(tasks.get-current-time.results.current-date-unix)
      taskRef:
        kind: ClusterTask
        name: openshift-client
      runAfter:
        - update-deployment-dev
    - name: update-kustomize-repo
      params:
        - name: gitRepositoryUrl
          value: $(params.git-source-url)
        - name: imageTag
          value: >-
            $(params.remote-image):$(tasks.get-current-time.results.current-date-unix)
        - name: verbose
          value: "true"
      runAfter:
        - tag-image
      taskRef:
        kind: Task
        name: update-kustomize-repo
      workspaces:
        - name: repository
          workspace: git-prod
  workspaces:
    - name: app-source
    - name: maven-settings
    - name: git-prod
